/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pizzaheaven.views;

import java.awt.BorderLayout;
import java.awt.event.WindowEvent;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import pizzaheaven.controllers.DrinksController;
import pizzaheaven.controllers.ImagesController;
import pizzaheaven.controllers.PizzaController;
import pizzaheaven.helpers.ImageHelpers;
import pizzaheaven.helpers.StringHelpers;
import pizzaheaven.models.Drink;
import pizzaheaven.models.Image;
import pizzaheaven.models.Pizza;
import pizzaheaven.models.Session;

/**
 *
 * @author dan
 */
public class FrmDrink extends javax.swing.JFrame {

    private Boolean modified = false;
    private Boolean editMode = false;
    /**
     * Creates new form FrmDrinks
     */
    public FrmDrink() {
        initComponents();
        initialiseImageCombo();
    }
    
    public FrmDrink(Drink drink) {
        initComponents();
        initialiseImageCombo();
        editMode = true;
        txtName.setEnabled(false);
        this.txtName.setText(drink.getName());
        this.txtDescription.setText(drink.getDescription());
        String[] parts = drink.getLargePrice().split(Pattern.quote("."));
        this.txtLargePricePound.setValue(Integer.valueOf(parts[0]));
        this.txtLargePricePence.setValue(Integer.valueOf(parts[1]));
        parts = drink.getMediumPrice().split(Pattern.quote("."));
        this.txtMediumPricePound.setValue(Integer.valueOf(parts[0]));
        this.txtMediumPricePence.setValue(Integer.valueOf(parts[1]));
        parts = drink.getSmallPrice().split(Pattern.quote("."));
        this.txtSmallPricePound.setValue(Integer.valueOf(parts[0]));
        this.txtSmallPricePence.setValue(Integer.valueOf(parts[1]));
        this.txtSmallDrinkName.setText(drink.getSmallSize());
        this.txtMediumDrinkName.setText(drink.getMediumSize());
        this.txtLargeDrinkName.setText(drink.getLargeSize());
        initialiseImageCombo();
        for (int i = 0; i < this.comboImages.getItemCount(); i++) {
            Image selectedImage = (Image)(Object)comboImages.getItemAt(i);
            if (selectedImage.getName().equals(drink.getImage())) {
                comboImages.setSelectedIndex(i);
            }
        }
    }
    
    private void initialiseImageCombo() {
        JComboBox temp = new JComboBox(((ImagesController)Session.get().getController("ImagesController")).get());
        this.comboImages.setModel(temp.getModel());
    }
    
    private Image getSelectedImage() {
        Object selectedObject = (Object)this.comboImages.getSelectedItem();
        if (selectedObject instanceof Image) {
            return (Image)selectedObject;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSmallPricePound = new javax.swing.JSpinner();
        txtMediumPricePound = new javax.swing.JSpinner();
        txtLargePricePound = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtSmallPricePence = new javax.swing.JSpinner();
        txtMediumPricePence = new javax.swing.JSpinner();
        txtLargePricePence = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        comboImages = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlImagePreview = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnUploadImage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSmallDrinkName = new javax.swing.JTextField();
        txtMediumDrinkName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtLargeDrinkName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pizza Heaven - Manager Application - Drinks");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel3.setText("Small Drink Price");

        btnClose.setText("Cancel");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel6.setText("Image Name");
        jLabel6.setToolTipText("");

        txtSmallPricePound.setModel(new javax.swing.SpinnerNumberModel());

        txtMediumPricePound.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        txtLargePricePound.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel5.setText("£");

        jLabel9.setText("£");

        btnSave.setText("Save ");
        btnSave.setToolTipText("Save & Close");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtSmallPricePence.setModel(new javax.swing.SpinnerNumberModel());

        txtMediumPricePence.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        txtLargePricePence.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel7.setText("Medium Drink Price");

        jLabel2.setText("Drink Description");

        jLabel8.setText("Large Drink Price ");

        txtDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescriptionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescriptionKeyTyped(evt);
            }
        });

        comboImages.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboImages.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboImagesItemStateChanged(evt);
            }
        });
        comboImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboImagesActionPerformed(evt);
            }
        });

        jLabel10.setText("£");

        jLabel11.setText("p");

        jLabel12.setText("p");

        jLabel13.setText("p");

        pnlImagePreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlImagePreview.setPreferredSize(null);

        jLabel14.setText("Image Preview");
        jLabel14.setToolTipText("");

        btnUploadImage.setText("Upload Image...");
        btnUploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadImageActionPerformed(evt);
            }
        });

        jLabel1.setText("Drink Name");

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        jLabel4.setText("Small Drink Size");

        jLabel15.setText("Medium Drink Size");

        jLabel16.setText("Large Drink Size");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLargeDrinkName)
                            .addComponent(txtDescription)
                            .addComponent(txtName)
                            .addComponent(txtSmallDrinkName)
                            .addComponent(txtMediumDrinkName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLargePricePound, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMediumPricePound, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSmallPricePound, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLargePricePence, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMediumPricePence, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSmallPricePence, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUploadImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(pnlImagePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboImages, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSmallDrinkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtMediumDrinkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtLargeDrinkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSmallPricePound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMediumPricePound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLargePricePound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSmallPricePence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMediumPricePence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLargePricePence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboImages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUploadImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(pnlImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        if (modified) {
            int result = JOptionPane.showConfirmDialog(this, "You have unsaved changes. Are you sure you want to exit?", "Unsaved Changes", JOptionPane.YES_NO_OPTION);
            if (result != JOptionPane.YES_OPTION) {
                return;
            }
        }
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtName.getText().contains("'")) {
            JOptionPane.showMessageDialog(this, "Drink names cannot contain an apostrophy!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Drink drinkToAdd = new Drink();
        drinkToAdd.setDescription(this.txtDescription.getText());
        drinkToAdd.setName(this.txtName.getText());
        drinkToAdd.setSmallPrice(String.valueOf(this.txtSmallPricePound.getValue())
            + "." + StringHelpers.formatPence((Integer)this.txtSmallPricePence.getValue()));
        drinkToAdd.setSmallSize(txtSmallDrinkName.getText());
        drinkToAdd.setMediumPrice(String.valueOf(this.txtMediumPricePound.getValue())
            + "." + StringHelpers.formatPence((Integer)this.txtMediumPricePence.getValue()));
        drinkToAdd.setMediumSize(txtMediumDrinkName.getText());
        drinkToAdd.setLargePrice(String.valueOf(this.txtLargePricePound.getValue())
            + "." + StringHelpers.formatPence((Integer)this.txtLargePricePence.getValue())); 
        drinkToAdd.setLargeSize(txtLargeDrinkName.getText());
        drinkToAdd.setImage(getSelectedImage().getName());
        int apiResult;
        if (!editMode) {
            apiResult = ((DrinksController)Session.get().getController("DrinksController")).add(drinkToAdd);
        } else {
            apiResult = ((DrinksController)Session.get().getController("DrinksController")).update(drinkToAdd);
        }
        if (apiResult == 201 || apiResult == 204) {
            int result = JOptionPane.showConfirmDialog(this, "Your Drink " + drinkToAdd.getName() + (apiResult == 201 ? " has been created" : " has been updated"), "Save Confirmation", JOptionPane.DEFAULT_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                modified = false;
                this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error contacting the API. Response code: " + apiResult + ". If the problem persists, please seek technical advice", "API Connectivity Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriptionKeyPressed
        // TODO add your handling code here:
        if (txtDescription.getText().length() >= 250) {
            evt.consume();
        } else {
            modified = true;
        }
    }//GEN-LAST:event_txtDescriptionKeyPressed

    private void txtDescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriptionKeyTyped
        // TODO add your handling code here:
        if (txtDescription.getText().length() >= 250) {
            evt.consume();
        } else {
            modified = true;
        }
    }//GEN-LAST:event_txtDescriptionKeyTyped

    private void comboImagesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboImagesItemStateChanged
        // TODO add your handling code here:
        Pizza selectedPizza = ((PizzaController)Session.get().getController("PizzaController")).get(txtName.getText());
        if (selectedPizza != null) {
            if (!getSelectedImage().getName().equals(selectedPizza.getImage()))
            modified = true;
            else
            modified = false;
        }
    }//GEN-LAST:event_comboImagesItemStateChanged

    private void comboImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboImagesActionPerformed
        // TODO add your handling code here:
        Image[] imageList = ((ImagesController)Session.get().getController("ImagesController")).get();
        pnlImagePreview.removeAll();
        for (Image image : imageList) {
            if (image.getName().equals(getSelectedImage().getName())) {
                JLabel temp = new JLabel();
                Icon icon = new ImageIcon(ImageHelpers.base64Decode(image));
                temp.setIcon(icon);
                pnlImagePreview.add(temp, BorderLayout.CENTER);
                pnlImagePreview.revalidate();
                pnlImagePreview.repaint();
            }
        }

    }//GEN-LAST:event_comboImagesActionPerformed

    private void btnUploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadImageActionPerformed
        // TODO add your handling code here:
        FrmImage frmImage = new FrmImage();
        frmImage.setVisible(true);
        this.setEnabled(false);

        frmImage.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                imageUploadFormClosed(evt);
            }
        });
    }//GEN-LAST:event_btnUploadImageActionPerformed

    private void imageUploadFormClosed(java.awt.event.WindowEvent evt) {
        this.setEnabled(true);
        this.initialiseImageCombo();
    } 
    
    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNameKeyPressed

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
        if (txtName.getText().length() >= 20) {
            evt.consume();
        } else {
            modified = true;
        }
    }//GEN-LAST:event_txtNameKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (modified) {
            int result = JOptionPane.showConfirmDialog(this, "You have unsaved changes Are you sure you want to exit?", "Unsaved Changes", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.NO_OPTION) {
                this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            } else {
                this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDrink().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClose;
    public javax.swing.JButton btnSave;
    private javax.swing.JButton btnUploadImage;
    private javax.swing.JComboBox<String> comboImages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlImagePreview;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtLargeDrinkName;
    private javax.swing.JSpinner txtLargePricePence;
    private javax.swing.JSpinner txtLargePricePound;
    private javax.swing.JTextField txtMediumDrinkName;
    private javax.swing.JSpinner txtMediumPricePence;
    private javax.swing.JSpinner txtMediumPricePound;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSmallDrinkName;
    private javax.swing.JSpinner txtSmallPricePence;
    private javax.swing.JSpinner txtSmallPricePound;
    // End of variables declaration//GEN-END:variables
}
