/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pizzaheaven.views;

import java.awt.BorderLayout;
import java.awt.event.WindowEvent;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import pizzaheaven.controllers.ImagesController;
import pizzaheaven.controllers.ToppingsController;
import pizzaheaven.helpers.ImageHelpers;
import pizzaheaven.helpers.StringHelpers;
import pizzaheaven.models.Image;
import pizzaheaven.models.Session;
import pizzaheaven.models.Topping;

/**
 *
 * @author dan
 */
public class FrmTopping extends javax.swing.JFrame {
    
    private boolean modified = false;
    private boolean editMode = false;
    /**
     * Creates new form FrmToppings
     */
    public FrmTopping() {
        initComponents();
        initialiseImageCombo();
    }
    
    public FrmTopping(Topping topping) {
        initComponents();
        initialiseImageCombo();
        editMode = true;
        txtToppingName.setEnabled(false);
        this.txtToppingName.setText(topping.getName());
        this.txtToppingDescription.setText(topping.getDescription());
        this.txtToppingPricePound.setValue(Double.valueOf(topping.getPrice().split(Pattern.quote("."))[0]));
        this.txtToppingPricePence.setValue(Double.valueOf(topping.getPrice().split(Pattern.quote("."))[1]));
        this.txtHeatRating.setValue(Double.valueOf(topping.getHeatRating()));
        initialiseImageCombo();
         for (int i = 0; i < this.cboImages.getItemCount(); i++) {
            Image selectedImage = (Image)(Object)cboImages.getItemAt(i);
            if (selectedImage.getName().equals(topping.getImage())) {
                cboImages.setSelectedIndex(i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUploadImage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtToppingDescription = new javax.swing.JTextField();
        cboImages = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHeatRating = new javax.swing.JSpinner();
        txtToppingName = new javax.swing.JTextField();
        txtToppingPricePound = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlImagePreview = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        txtToppingPricePence = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pizza Heaven - Manager Application -  Toppings");
        setResizable(false);

        btnUploadImage.setText("Upload Image...");
        btnUploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadImageActionPerformed(evt);
            }
        });

        jLabel2.setText("Topping Description");

        txtToppingDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtToppingDescriptionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtToppingDescriptionKeyTyped(evt);
            }
        });

        cboImages.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboImagesActionPerformed(evt);
            }
        });

        jLabel3.setText("Topping Price");

        btnClose.setText("Cancel");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel4.setText("Topping Heat Rating");

        jLabel6.setText("Image Name");
        jLabel6.setToolTipText("");

        txtHeatRating.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 3.0d, 1.0d));

        txtToppingName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtToppingNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtToppingNameKeyTyped(evt);
            }
        });

        txtToppingPricePound.setModel(new javax.swing.SpinnerNumberModel());

        jLabel14.setText("Image Preview");
        jLabel14.setToolTipText("");

        jLabel5.setText("£");

        jLabel13.setText("p");

        pnlImagePreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlImagePreview.setPreferredSize(null);

        btnSave.setText("Save ");
        btnSave.setToolTipText("Save & Close");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtToppingPricePence.setModel(new javax.swing.SpinnerNumberModel());

        jLabel1.setText("Topping Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtToppingPricePound, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtToppingPricePence)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addComponent(txtToppingName)
                            .addComponent(txtToppingDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pnlImagePreview, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                                    .addComponent(btnUploadImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboImages, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHeatRating, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtToppingName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtToppingDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtToppingPricePence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtToppingPricePound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeatRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboImages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUploadImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(pnlImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadImageActionPerformed
        // TODO add your handling code here:
        FrmImage frmImage = new FrmImage();
        frmImage.setVisible(true);
    }//GEN-LAST:event_btnUploadImageActionPerformed

    private void txtToppingDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtToppingDescriptionKeyPressed
        // TODO add your handling code here:
        if (txtToppingName.getText().length() >= 250) {
            evt.consume();
        } else {
            modified = true;
        }
    }//GEN-LAST:event_txtToppingDescriptionKeyPressed

    private void txtToppingDescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtToppingDescriptionKeyTyped
        // TODO add your handling code here:
        if (txtToppingDescription.getText().length() >= 250) {
            evt.consume();
        } else {
            modified = true;
        }
    }//GEN-LAST:event_txtToppingDescriptionKeyTyped

    private void initialiseImageCombo() {
        JComboBox temp = new JComboBox(((ImagesController)Session.get().getController("ImagesController")).get());
        this.cboImages.setModel(temp.getModel());
    }
    
    private Image getSelectedImage() {
        Object selectedObject = (Object)this.cboImages.getSelectedItem();
        if (selectedObject instanceof Image) {
            return (Image)selectedObject;
        }
        return null;
    }
    
     private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        // TODO add your handling code here:
        if (modified) {
            int result = JOptionPane.showConfirmDialog(this, "You have unsaved changes Are you sure you want to exit?", "Unsaved Changes", JOptionPane.YES_NO_OPTION);
            if (result != JOptionPane.YES_OPTION) {
                return;
            } 
        }
    }  
    
    private void cboImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboImagesActionPerformed
        // TODO add your handling code here:
        Image[] imageList = ((ImagesController)Session.get().getController("ImagesController")).get();
        pnlImagePreview.removeAll();
        for (Image image : imageList) {
            if (image.getName().equals(getSelectedImage().getName())) {
                JLabel temp = new JLabel();
                Icon icon = new ImageIcon(ImageHelpers.base64Decode(image));
                temp.setIcon(icon);
                pnlImagePreview.add(temp, BorderLayout.CENTER);
                pnlImagePreview.revalidate();
                pnlImagePreview.repaint();
            }
        }
    }//GEN-LAST:event_cboImagesActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        if (modified) {
            int result = JOptionPane.showConfirmDialog(this, "You have unsaved changes. Are you sure you want to exit?", "Unsaved Changes", JOptionPane.YES_NO_OPTION);
            if (result != JOptionPane.YES_OPTION) {
                return;
            }
        }
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtToppingNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtToppingNameKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtToppingNameKeyPressed

    private void txtToppingNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtToppingNameKeyTyped
        // TODO add your handling code here:
        if (txtToppingName.getText().length() >= 20) {
            evt.consume();
        } else {
            modified = true;
        }
    }//GEN-LAST:event_txtToppingNameKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Topping toppingToAdd = new Topping();
        toppingToAdd.setName(this.txtToppingName.getText());
        toppingToAdd.setDescription(this.txtToppingDescription.getText());
        toppingToAdd.setHeatRating(String.valueOf(this.txtHeatRating.getValue()));
        toppingToAdd.setPrice(String.valueOf(this.txtToppingPricePound.getValue())
            + "." + StringHelpers.formatPence((Integer)this.txtToppingPricePound.getValue()));
        toppingToAdd.setImage(getSelectedImage().getName());
        int apiResult;
        if (!editMode) {
            apiResult = ((ToppingsController)Session.get().getController("ToppingsController")).add(toppingToAdd);
        } else {
            apiResult = ((ToppingsController)Session.get().getController("ToppingsController")).update(toppingToAdd);
        }
        if (apiResult == 201 || apiResult == 204) {
            int result = JOptionPane.showConfirmDialog(this, "Your topping " + toppingToAdd.getName() + (apiResult == 201 ?  "  has been created" : "has been updated"), "Save Confirmation", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                modified = false;
                this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error contacting the API. Response code: " + apiResult + ". If the problem persists, please seek technical advice", "API Connectivity Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTopping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClose;
    public javax.swing.JButton btnSave;
    private javax.swing.JButton btnUploadImage;
    private javax.swing.JComboBox<String> cboImages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlImagePreview;
    private javax.swing.JSpinner txtHeatRating;
    private javax.swing.JTextField txtToppingDescription;
    private javax.swing.JTextField txtToppingName;
    private javax.swing.JSpinner txtToppingPricePence;
    private javax.swing.JSpinner txtToppingPricePound;
    // End of variables declaration//GEN-END:variables
}
